// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart;
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD86cHbZ6Fie4IiVVoJNf1r9cozlPtJoEM',
    appId: '1:245128443348:web:placeholder',
    messagingSenderId: '245128443348',
    projectId: 'exercise-app-83ac2',
    authDomain: 'exercise-app-83ac2.firebaseapp.com',
    storageBucket: 'exercise-app-83ac2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86cHbZ6Fie4IiVVoJNf1r9cozlPtJoEM',
    appId: '1:245128443348:android:6437a25db4f88156df5241',
    messagingSenderId: '245128443348',
    projectId: 'exercise-app-83ac2',
    storageBucket: 'exercise-app-83ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86cHbZ6Fie4IiVVoJNf1r9cozlPtJoEM',
    appId: '1:245128443348:ios:placeholder',
    messagingSenderId: '245128443348',
    projectId: 'exercise-app-83ac2',
    storageBucket: 'exercise-app-83ac2.firebasestorage.app',
    iosBundleId: 'com.company.exercise',
  );
}
